/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-container-low": "#f6f4e9",
        "on-primary-fixed-variant": "#514700",
        "on-error": "#ffffff",
        "primary-container": "#eed202",
        "secondary": "#3b6934",
        "on-primary-fixed": "#211c00",
        "tertiary": "#4d6453",
        "primary-fixed-dim": "#e1c700",
        "on-secondary-container": "#3f6d38",
        "on-secondary": "#ffffff",
        "tertiary-container": "#bfd8c3",
        "on-surface-variant": "#4b4732",
        "surface-container-highest": "#e4e3d8",
        "tertiary-fixed": "#d0e9d4",
        "surface-container": "#f0eee3",
        "on-tertiary-fixed-variant": "#364c3c",
        "primary-fixed": "#ffe330",
        "on-secondary-fixed": "#002201",
        "on-background": "#1b1c16",
        "inverse-on-surface": "#f3f1e6",
        "surface-container-high": "#eae8de",
        "secondary-container": "#b9eeab",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e3d8",
        "on-primary-container": "#675a00",
        "inverse-surface": "#30312a",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#a1d494",
        "surface-bright": "#fcfaef",
        "on-tertiary-container": "#495f4f",
        "on-secondary-fixed-variant": "#23501e",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#0b2013",
        "surface-dim": "#dcdad0",
        "outline": "#7d7760",
        "on-surface": "#1b1c16",
        "tertiary-fixed-dim": "#b4cdb8",
        "primary": "#6c5e00",
        "error": "#ba1a1a",
        "secondary-fixed": "#bcf0ae",
        "error-container": "#ffdad6",
        "inverse-primary": "#e1c700",
        "surface-container-lowest": "#ffffff",
        "background": "#fcfaef",
        "outline-variant": "#cec6ab",
        "surface-tint": "#6c5e00",
        "surface": "#fcfaef"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "base": "8px",
        "gutter": "12px",
        "lg": "24px",
        "xl": "40px",
        "md": "16px",
        "container-margin": "20px",
        "sm": "12px"
      },
      "fontFamily": {
        "headline-lg": ["Outfit", "sans-serif"],
        "title-md": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "label-md": ["Outfit", "sans-serif"],
        "body-lg": ["Outfit", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "body-sm": ["Outfit", "sans-serif"],
        "sans": ["Outfit", "sans-serif"]
      },
      "fontSize": {
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
